version: '3.0'

services:

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app-node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - desafio2
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3001:3001"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: app-nginx
    networks:
      - desafio2
    ports:
      - "8080:80"
    depends_on:
      - node

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=marcosdeli
    networks:
      - desafio2

networks:
  desafio2:
    driver: bridge